name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run jest tests
        run: |
          yarn test

      - name: Run test runner (default config)
        run: |
          yarn build
          yarn test-storybook:ci

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2.3.1
        if: failure()
        with:
          name: snapshotdiff
          path: __snapshots__/__diff_output__
          if-no-files-found: ignore

      - name: Run test runner (story store v7)
        run: |
          yarn build
          STORY_STORE_V7=true yarn test-storybook:ci

      - name: Run test runner (stories json mode)
        run: |
          yarn build
          yarn test-storybook:ci-json